version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
jobs:
  build_and_test:
    docker:
      - image: circleci/node:10-buster
    steps:
      - checkout
      - run:
          name: Check node version
          command: node -v
      - restore_cache:
          name: Restore yarn cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --immutable
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Node tests
          command: yarn test
      - run:
          name: Browser tests
          command: yarn test-browser
      - save_cache:
          name: Save yarn cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - store_artifacts:
          path: coverage